name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Windows latest MSVC"
            os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            build_type: Release
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: configure
        run: >
          cmake
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE:STRING=${{ matrix.build_type }}
          -B build
          -S .
      - name: build
        run: cmake --build build --config ${{ matrix.build_type }}
      - name: build & run tests
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        run: cmake --build build --target run_tests --config ${{ matrix.build_type }}
